### PR TITLE
Added Units KiloJoulePerCubicMeter & BtuPerCubicFeet

### PR DESCRIPTION
**Pull request by johankristiansson**

### CODE REVIEW

**Comment by jonaskello** [comment]
Seems code coverage is not working. Currently we are using nyc. We should switch to using jest for tests because it has built-in support for code coverage.

**Comment by jonaskello** [comment]
@johankristiansson I have switched to jest in master, try rebasing this PR on master.

**Comment by johankristiansson** [comment]
@jonaskello Rebased on master

**Comment by jonaskello** [comment]
@johankristiansson You closed the PR... should it not be merged?

**Pull request closed without merging**
